package routers

import (
	"backend/pkg/database"
	_ "backend/services/userService/docs" // docs is generated by Swag CLI, you have to import it.
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/spf13/viper"
	"github.com/swaggo/http-swagger/v2"
)

func RegisterRoutes(router *chi.Mux, db *database.DB) {
	router.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("\"live\": \"ok\""))
	})

	router.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL(fmt.Sprintf("http://localhost:%s/swagger/doc.json", viper.GetString("PORT")))), //The url pointing to API definition
	)

	router.Route("/api", func(r chi.Router) {
		// Add routes
		UserRoutes(r, db)
		OauthRoutes(r, db)
	})
}
