info:
  contact:
    email: support@swagger.io
    name: Vacaition API Support
    url: http://www.swagger.io/support
  description: This server is used for creating new users and conduct authentication
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: User/Auth API
  version: "1.0"
paths: {}
swagger: "2.0"
