package routers

import (
	_ "backend/docs/tripService" // docs is generated by Swag CLI, you have to import it.
	"backend/pkg/database"
	"backend/pkg/middlewares"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/spf13/viper"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

func RegisterRoutes(router *chi.Mux, db *database.DB) {
	router.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("\"live\": \"ok\""))
	})

	router.Get("/api/swagger/*", httpSwagger.Handler(
		httpSwagger.URL(fmt.Sprintf("http://%s/api/swagger/doc.json", viper.GetString("URL")))), //The url pointing to API definition
	)

	router.Route("/api", func(r chi.Router) {
		r.Use(middlewares.UserClaims)
		// Add routes
		TripRoutes(r, db)
		StopRoutes(r, db)
	})
}
